version: '2'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    networks:
      - internal
    depends_on:
      - server
#  http://localhost:8080/client

  server:
    container_name: server
    build:
      context: ../server
      dockerfile: Dockerfile
    networks:
      - internal
#  ссылки для открытия: http://localhost:8080/file, http://localhost:8080/server

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - client
    ports:
      - "8080:8080"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
networks:
  internal:
    driver: bridge